/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("com.gradle.enterprise").version("3.11.4")
}

rootProject.name = "hedera-transaction-tool"
include(":tools-ui")
include(":tools-core")
include(":tools-integration")
include(":tools-cli")

gradleEnterprise {
    buildScan {
        termsOfServiceUrl = "https://gradle.com/terms-of-service"
        termsOfServiceAgree = "yes"
    }
}