/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("com.hedera.hashgraph.java-conventions")
}

dependencies {
    implementation(project(":tools-core"))
    implementation(libs.bundles.logging)
    implementation(libs.bundles.jackson)
    implementation(libs.bundles.bouncycastle)
    implementation(libs.picocli)
    implementation(libs.eddsa)
    implementation(libs.grpc.core)
    implementation(libs.gson)
//    implementation(libs.json)
    implementation(libs.zt.zip)
    implementation(libs.httpclient)
    implementation(libs.commons.io)
    implementation(libs.passpol)
    implementation(libs.jetbrains.annotations)
    testImplementation(testLibs.bundles.junit)
//    testRuntimeOnly(testLibs.junit.jupiter.engine)
}

description = "tools-cli"