/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("com.hedera.hashgraph.java-conventions")
}

dependencies {
    implementation(project(":tools-core"))
    implementation("com.hedera.hashgraph:sdk:2.19.0")
    implementation("info.picocli:picocli:4.6.1")
    implementation("net.i2p.crypto:eddsa:0.3.0")
    implementation("io.grpc:grpc-core:1.44.0")
    implementation("com.google.code.gson:gson:2.8.9")
    implementation("org.zeroturnaround:zt-zip:1.14")
    implementation("org.slf4j:slf4j-api:1.7.30")
    implementation("org.apache.logging.log4j:log4j-api:2.17.1")
    implementation("org.apache.logging.log4j:log4j-core:2.17.1")
    implementation("org.apache.logging.log4j:log4j-slf4j-impl:2.17.1")
    implementation("org.json:json:20210307")
    implementation("org.apache.httpcomponents:httpclient:4.5.13")
    implementation("commons-io:commons-io:2.8.0")
    implementation("org.bouncycastle:bcprov-jdk15on:1.69")
    implementation("org.bouncycastle:bcpkix-jdk15on:1.69")
    implementation("com.codahale:passpol:0.7.0")
    implementation("com.fasterxml.jackson.core:jackson-annotations:2.13.3")
    implementation("com.fasterxml.jackson.core:jackson-core:2.13.3")
    implementation("com.fasterxml.jackson.core:jackson-databind:2.13.3")
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.8.0-M1")
    testImplementation("org.junit.jupiter:junit-jupiter-params:5.8.0-M1")
    testImplementation("org.junit.jupiter:junit-jupiter-engine:5.8.0-M1")
}

description = "tools-cli"
