/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    application
    id("com.hedera.hashgraph.java-conventions")
    id("org.openjfx.javafxplugin") version "0.0.13"
}

dependencies {
    implementation(project(":tools-core"))
    implementation(libs.bundles.logging)
    implementation(libs.bundles.jackson)
    implementation(libs.bundles.bouncycastle)
    implementation(libs.gson)
    implementation(libs.commons.lang3)
    implementation(libs.protobuf.java.util)
    implementation(libs.eddsa)
    implementation(libs.commons.lang3)
    implementation(libs.commons.collections4)
    implementation(libs.controlsfx)
    implementation(libs.zt.zip)
    implementation(libs.httpclient)
    implementation(libs.commons.io)
    implementation(libs.passpol)
    implementation(libs.jetbrains.annotations)
    testImplementation(testLibs.bundles.junit)
    testImplementation(testLibs.testfx.core)
    testImplementation(testLibs.testfx.junit)
    testImplementation(testLibs.testfx.openjfx.monocle)
}

application {
    mainClass.set("Main.java")
}

javafx {
    version = "19"
    modules("javafx.controls", "javafx.fxml")
}

description = "tools-ui"