#!/usr/bin/env sh

#
# Hedera Transaction Tool
#
# Copyright (C) 2018 - 2021 Hedera Hashgraph, LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

#sudo chown root:wheel "/Applications"


echo "Moving application out of containing folder."
[[ -e "/Applications/TransactionTools.localized/TransactionTools.app" ]] && mv -f /Applications/TransactionTools.localized/TransactionTools.app /Applications/TransactionTools.app

echo "Removing TransactionTools folder"
[[ -e "/Applications/TransactionTools.localized/" ]] && rm -rf /Applications/TransactionTools.localized/

chmod a+rX "/Applications"
chmod +r "/Applications/TransactionTools.app/Contents/app/"*.jar
open -a "/Applications/TransactionTools.app"
exit 0
