/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    java
    jacoco
}

repositories {
    mavenCentral()
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }

    maven {
        url = uri("https://jcenter.bintray.com/")
    }

    maven {
        url = uri("https://art.swirlds.com/artifactory/swirlds")
    }
}

dependencies {
    implementation("com.hedera.hashgraph:sdk:2.19.0")
}

group = "com.hedera.hashgraph"
version = "0.12.2"
java.sourceCompatibility = JavaVersion.VERSION_17

//publishing {
//    publications.create<MavenPublication>("maven") {
//        from(components["java"])
//    }
//}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc> {
    options.encoding = "UTF-8"
    (options as StandardJavadocDocletOptions)
        .tags("apiNote:a:API Note:", "implSpec:a:Implementation Requirements:", "implNote:a:Implementation Note:")
}

tasks.named<Test>("test") {
    useJUnitPlatform()
}