/*
 * Hedera Transaction Tool
 *
 * Copyright (C) 2018 - 2021 Hedera Hashgraph, LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.hedera.hashgraph.client.core.constants;

public class ErrorMessages {


	private ErrorMessages() {
		throw new IllegalStateException("Constants class");
	}

	public static final String MISSING_FIELD_ERROR_MESSAGE = "Missing field {}";
	public static final String CANNOT_PARSE_ERROR_MESSAGE = "Cannot parse: {}";
	public static final String FILE_DOES_NOT_EXIST_ERROR_MESSAGE = "{} does not exist";
	public static final String CANNOT_PARSE_IDENTIFIER_ERROR_MESSAGE = "Cannot load identifier {}";
	public static final String CANNOT_VALIDATE_INPUT_ERROR_MESSAGE = "Cannot validate input";
	public static final String NON_ZERO_TOTAL_ERROR_MESSAGE =
			"The total of all transfers must add to 0. The current total is {}";
	public static final String CANNOT_LOAD_TRANSACTION_ERROR_MESSAGE = "Cannot load transaction from file";
	public static final String CANNOT_PARSE_TYPE_ERROR_MESSAGE = "Cannot load type";
	public static final String CANNOT_READ_FILE_ATTRIBUTES_ERROR_MESSAGE = "Cannot read file attributes";
	public static final String EMPTY_KEYSTORE_ERROR_MESSAGE = "KeyStore is currently empty and cannot be persisted.";
	public static final String UNKNOWN_KEY_ERROR_MESSAGE =
			"The app does not have information regarding this public key. Contact your " +
					"administrator for more details";
	public static final String ACCOUNTS_FOLDER_ERROR_MESSAGE = "Error reading Accounts directory";
	public static final String PUBLIC_KEY_MISMATCH_MESSAGE =
			"We could not match the public key generated by the recovery process to the one we have on " +
					"file" +
					". The key will not be overwritten";
	public static final String NOT_EMPTY_FIELD_ERROR_MESSAGE = "Cannot add a transaction to a non empty field";
	public static final String OUT_OF_RANGE_EXCEPTION_MESSAGE = "Out of range exception: ";
	public static final String NULL_OBJECT_COMPARISON_ERROR_MESSAGE = "Cannot compare to a null object";
	public static final String INCOMPATIBLE_TYPES_ERROR_MESSAGE = "Incompatible types for comparison";
	public static final String PASSWORD_CANNOT_BE_EMPTY_ERROR_MESSAGE = "Password cannot be empty";
	public static final String MNEMONIC_CANNOT_BE_NULL_ERROR_MESSAGE = "Mnemonic cannot be null";
	public static final String COULD_NOT_CALCULATE_HASH_OF_THE_FILE = "Could not calculate the hash of the file";
	public static final String POSITIVE_NUMBER_CURRENCY_ERROR_MESSAGE = "Currency amount must be a positive number";
	public static final String FEE_PAYER_NOT_SET_ERROR_MESSAGE =
			"The fee payer account has not been set. Please go to the settings tab and set the default payer in order " +
					"to request account information from the network.";
}
