/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("com.hedera.hashgraph.java-conventions")
    id("org.openjfx.javafxplugin") version "0.0.13"
}

dependencies {
    implementation("org.testfx:openjfx-monocle:jdk-12.0.1+2")
    implementation("pl.pragmatists:JUnitParams:1.1.1")
    testImplementation(project(":tools-core"))
    testImplementation(project(":tools-ui"))
    testImplementation(project(":tools-cli"))
    testImplementation("org.junit.jupiter:junit-jupiter:5.8.0-M1")
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.8.0-M1")
    testImplementation("org.junit.jupiter:junit-jupiter-params:5.8.0-M1")
    testImplementation("org.junit.jupiter:junit-jupiter-engine:5.8.0-M1")
    testImplementation("org.junit.vintage:junit-vintage-engine:5.8.0-M1")
    testImplementation("org.apache.logging.log4j:log4j-api:2.17.1")
    testImplementation("commons-io:commons-io:2.8.0")
    testImplementation("com.google.code.gson:gson:2.8.9")
    testImplementation("org.testfx:testfx-core:4.0.16-alpha")
    testImplementation("org.testfx:testfx-junit:4.0.16-alpha")
    testImplementation("org.testfx:testfx-junit5:4.0.16-alpha")
    testImplementation("org.controlsfx:controlsfx:11.1.0")
    testImplementation("com.opencsv:opencsv:5.6")
}

javafx {
    version = "19"
    modules("javafx.controls", "javafx.fxml")
}

description = "tools-integration"
