/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("com.hedera.hashgraph.java-conventions")
    id("org.openjfx.javafxplugin") version "0.0.13"
}

dependencies {
    testImplementation(project(":tools-core"))
    testImplementation(project(":tools-ui"))
    testImplementation(project(":tools-cli"))
    testImplementation(libs.bundles.logging)
    testImplementation(libs.commons.io)
    testImplementation(libs.gson)
    testImplementation(libs.controlsfx)
    testImplementation(libs.opencsv)
    testImplementation(testLibs.testfx.core)
    testImplementation(testLibs.testfx.junit)
    testImplementation(testLibs.bundles.junit)
//    testRuntimeOnly(testLibs.junit.jupiter.engine)
    testRuntimeOnly(testLibs.testfx.openjfx.monocle)
}

javafx {
    version = "19"
    modules("javafx.controls", "javafx.fxml")
}

description = "tools-integration"