/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("com.hedera.hashgraph.java-conventions")
    id("org.openjfx.javafxplugin") version "0.0.13"
}

dependencies {
    implementation(libs.hedera.sdk)
    implementation(libs.bundles.logging)
    implementation(libs.bundles.bouncycastle)
    implementation(libs.jackson.databind)
    implementation(libs.eddsa)
    implementation(libs.protobuf.javalite)
    implementation(libs.protobuf.java.util)
    implementation(libs.commons.codec)
    implementation(libs.commons.io)
    implementation(libs.httpclient)
    implementation(libs.zt.zip)
    implementation(libs.opencsv)
    implementation(libs.picocli)
//    implementation(libs.json)
    implementation(libs.grpc.netty)
    implementation(libs.maven.artifact)
    implementation(libs.passpol)
    implementation(libs.jetbrains.annotations)
    testImplementation(testLibs.junitparams)
    testImplementation(testLibs.testfx.junit)
    testImplementation(testLibs.bundles.junit)
//    testRuntimeOnly(testLibs.junit.jupiter.engine)
    testRuntimeOnly(testLibs.testfx.openjfx.monocle)
}

javafx {
    version = "19"
    modules("javafx.controls", "javafx.fxml")
}

description = "tools-core"