/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("com.hedera.hashgraph.java-conventions")
    id("org.openjfx.javafxplugin") version "0.0.13"
}

dependencies {
    implementation("org.apache.logging.log4j:log4j-core:2.17.1")
    implementation("org.apache.logging.log4j:log4j-api:2.17.1")
    implementation("org.apache.logging.log4j:log4j-slf4j-impl:2.17.1")
    implementation("org.slf4j:slf4j-api:1.7.30")
    implementation("org.bouncycastle:bcprov-jdk15on:1.69")
    implementation("org.bouncycastle:bcpkix-jdk15on:1.69")
    implementation("org.bouncycastle:bcpg-jdk15on:1.69")
    implementation("net.i2p.crypto:eddsa:0.3.0")
    implementation("com.google.protobuf:protobuf-javalite:3.21.7")
    implementation("com.google.protobuf:protobuf-java-util:3.21.7")
    implementation("commons-codec:commons-codec:1.15")
    implementation("commons-io:commons-io:2.8.0")
    implementation("org.apache.httpcomponents:httpclient:4.5.13")
    implementation("org.zeroturnaround:zt-zip:1.14")
    implementation("com.opencsv:opencsv:5.6")
    implementation("info.picocli:picocli:4.6.1")
    implementation("com.fasterxml.jackson.core:jackson-databind:2.13.3")
    implementation("org.json:json:20210307")
    implementation("io.grpc:grpc-netty:1.44.0")
    implementation("org.apache.maven:maven-artifact:3.6.0")
    implementation("org.testfx:openjfx-monocle:jdk-12.0.1+2")
    implementation("pl.pragmatists:JUnitParams:1.1.1")
    implementation("com.codahale:passpol:0.7.0")
    implementation("org.jetbrains:annotations:13.0")
    testImplementation("org.junit.jupiter:junit-jupiter:5.8.0-M1")
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.8.0-M1")
    testImplementation("org.junit.jupiter:junit-jupiter-params:5.8.0-M1")
    testImplementation("org.junit.jupiter:junit-jupiter-engine:5.8.0-M1")
    testImplementation("org.junit.vintage:junit-vintage-engine:5.8.0-M1")
    testImplementation("org.testfx:testfx-junit5:4.0.16-alpha")
}

javafx {
    version = "19"
    modules("javafx.controls", "javafx.fxml")
}

description = "tools-core"
