name: openjdk_14_build
on:
  pull_request:
  push:
    branches: [ main, develop ]
    tags: [ v* ]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    env:
      MAVEN_CLI_OPTS: --batch-mode --no-transfer-progress
      TEST_ACCOUNT_ID: ${{ secrets.TEST_ACCOUNT_ID }}
      TEST_PRIVATE_KEY: ${{ secrets.TEST_PRIVATE_KEY }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install JDK
        uses: actions/setup-java@v2
        with:
          cache: 'maven'
          distribution: 'temurin'
          java-version: 17
      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Compile
        run: ./mvnw $MAVEN_CLI_OPTS clean compile
      - name: Unit Tests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN || '' }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN || '' }}
        run: ./mvnw $MAVEN_CLI_OPTS test -pl :tools-core
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: "*/target/surefire-reports/*.xml"
