name: openjdk_14_build
on:
  pull_request:
  push:
    branches: [ main, develop ]
    tags: [ v* ]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container: gcr.io/swirlds-registry/cci-openjdk-ghr:14.0.2
    env:
      MAVEN_OPTS: -Xmx5200m
      LC_ALL: C.UTF-8
      DEBIAN_FRONTEND: noninteractive
    timeout-minutes: 60
    steps:
      - run: apt-get -y install software-properties-common
      - run: add-apt-repository ppa:git-core/ppa
      - run: apt-get -y install git
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: mvn --version
      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Compile
        run: mvn -DskipTests clean compile
      - name: Unit Tests And Sonar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn test verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.pullrequest.github.repository=hashgraph/hedera-transaction-tool-demo -Dsonar.pullrequest.provider=github -Dsonar.qualitygate.wait=true -Dsonar.projectKey=com.hedera.hashgraph:hedera-transaction-tool
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: "*/target/surefire-reports/*.xml"
      - name: Post to a Slack channel
        uses: slackapi/slack-github-action@v1.16.0
        if: always()
        with:
          channel-id: ${{ secrets.SONAR_SLACK_CHANNEL }}
          payload: |
            {
              "attachments": [
                {
                    "color": "${{ (job.status == 'success' && '#35c908') || ((job.status == 'cancelled' && '##c98c08') || '#c92808') }}",
                    "blocks": [
                        {
                            "type": "section",
                            "text": {
                                "type": "mrkdwn",
                                "text": "*Transaction Tool Build ${{ job.status }}*"
                            },
                            "fields": [
                                {
                                    "type": "mrkdwn",
                                    "text": "*_Commit Author:_*"
                                },
                                {
                                    "type": "mrkdwn",
                                    "text": "*_Branch:_*"
                                },
                                {
                                    "type": "mrkdwn",
                                    "text": "${{github.actor}}"
                                },
                                {
                                    "type": "mrkdwn",
                                    "text": "${{github.ref_name}}"
                                }
                            ]
                        },
                        {
                            "type": "section",
                            "fields": [
                                {
                                    "type": "mrkdwn",
                                    "text": "*_Github Actions Build Number:_*"
                                },
                                {
                                    "type": "mrkdwn",
                                    "text": "*_SonarCloud Analysis:_*"
                                },
                                {
                                    "type": "mrkdwn",
                                    "text": "<${{github.server_url}}/${{github.repository}}/actions/runs/${{github.run_id}}|${{github.run_number}}>"
                                },
                                {
                                    "type": "mrkdwn",
                                    "text": "<https://sonarcloud.io/summary/new_code?branch=${{github.ref_name}}&id=com.hedera.hashgraph%3Ahedera-transaction-tool|${{github.ref_name}}>"
                                }
                            ]
                        },
                        {
                            "type": "section",
                            "text": {
                                "type": "mrkdwn",
                                "text": "*_Git Commit:_*\n${{github.sha}}"
                            }
                        }
                    ]
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_ACCESS_TOKEN }}