name: openjdk_14_build
on:
  pull_request:
  push:
    branches: [ main, develop ]
    tags: [ v* ]
jobs:
  build-and-test:
    runs-on: transaction-tools-linux-medium
    timeout-minutes: 180
    env:
      MAVEN_CLI_OPTS: --batch-mode --no-transfer-progress
      TEST_ACCOUNT_ID: ${{ secrets.TEST_ACCOUNT_ID }}
      TEST_PRIVATE_KEY: ${{ secrets.TEST_PRIVATE_KEY }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
        with:
          egress-policy: audit

      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Install JDK
        uses: actions/setup-java@v91d3aa4956ec4a53e477c4907347b5e3481be8c9 # v2.5.1
        with:
          cache: 'maven'
          distribution: 'temurin'
          java-version: 17

      - name: Cache SonarCloud packages
        uses: actions/cache@f5ce41475b483ad7581884324a6eca9f48f8dcc7 # v1.2.1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Compile
        run: ./mvnw $MAVEN_CLI_OPTS clean compile

      - name: Unit Tests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN || '' }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN || '' }}
        run: ./mvnw $MAVEN_CLI_OPTS test

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@b9f6c61d965bcaa18acc02d6daf706373a448f02 # v1.40
        if: always()
        with:
          files: "*/target/surefire-reports/*.xml"
